import type { NextPage } from 'next'
import Head from 'next/head'
import HomePage from '../src/components/HomePage'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AB Web Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/imageLogo.png" />
      </Head>
      <main>
        <HomePage />
      </main>
    </div>
  )
}

export default Home
